
# Application Entry Point
CodeGenerationController: false
CodeGenerationService: false
MaterialsValidationConfig: false
MaterialsValidationService: false
ProductionProvider: false
ReferenceData: false
RuleService: false
ValidatingMaterials: false

# Drivers
ProductionParameters: false
Driver: false
EarliestMfgDateDriver: false
LineDriver: false
ManufacturingOriginDriver: false
ProductionDateDriver: false
SampleManufacturingOriginDriver: false
SampleMfgDateDriver: false
ShiftDriver: false
ShortestShelfLifeDriver: false
SiteDriver: false

# Interpreters
ExpiryDateInterpreter: true
MfgDatesInterpreter: false
MfgOriginInterpreter: true

# Reference Data
ReferenceDataField: false
ReferenceDataRow: false
ReferenceDataTable: false

# Rules
Rule: false
GenerateExpiryRule: false
GenerateLotRule: false
InterpretExpiryRule: false
InterpretLotRule: false
RuleFragment: false

# Scopes
Scope: false
JobLotsExpiriesScope: false
MovePlanScope: false
MovesScope: false
PickListCandidateScope: false
PickListsScope: false

# Transitions
RuleWizardController: false
Wizard: false
Transition: false
GenerateExpiryTransition: false
GenerateLotTransition: false
InterpretExpiryTransition: false
InterpretLotTransition: false

# Validations
CanInterpretMfgDateValidator: true
CanRunValidations: true
ExpiryDateParsingValidator: true
ExpiryDateRangeValidator: true
ExpiryDateValidator: true
FinishedGoodProductionDateLimitValidator: true
ManufacturingOriginValidator: true
PickStrategyValidator: true
QualifiedItemsPresenceValidator: true
ShelfLifeValidator: true
StopShipDateRangeValidator: true
StopShipDateValidator: true
StopShipLimitValidator: true
ValidationPipeline: true

# Data Synching
ReferenceDataSyncer: false
LineObserver: false
ShiftObserver: false
SiteObserver: false
TableBuilderService: false

# Domain Master
Account: false
Customer: false
Job: false
Line: false
Shift: false
Site: false
