config:
  InventoryRoot:
    - '@hidden'
  UMLOptions:
    - '@opt vertical'
    - '@opt attributes'
    - '@opt operations'
    - '@hidden'

production lightblue:
  Job:
    - '@has - - - Pallet'
    - '@has - - - Production'
    - '@has - - - RejectItem'
    - '@has - - - Sku'

  JobReconciliation:
    - '@has - - - Job'

  Production:

  RejectItem:

master palegreen:
  BomItem:

  Customer:
    - '@has - - - Job'
    - '@has - - - Sku'

  FloorLocation extends Location:

  ItemClass:
    - '@has - - - Sku'
    - '@has - - - ZoningRule'

  Location:
    - '@has - - - InventoryDelta'
    - '@has - - - WarehouseZone'

  Line:
    - '@has - - - Job'

  Sku:
    - '@has - - - BomItem'
    - '@has - - - CurrentInventoryLevel'
    - '@has - - - InventoryDelta'

  WarehouseZone:
    - '@composed - - - ZoningRule'

  ZoningRule:

inventory lightcoral:
  CurrentInventoryLevel:
    - '@has - - - InventoryStatus'

  InventoryDelta:
    - '@has - - - InventoryStatus'

  InventoryStatus:

  Pallet:
    - '@has - - - InventoryDelta'
